; Output: encapsulated PostScript file with preview.



SET_PLOT, 'PS'

MAP_SET,/MERCATOR, 0, 0, /ISOTROPIC,LIMIT=[29,-116,49,-75]
MAP_GRID,/BOX_AXES,GLINESTYLE=0,GLINETHICK=5,LATDEL=2,LONDEL=2
MAP_CONTINENTS, LINETHICK=2,/USA


DEVICE, /CLOSE
